site_name: Лабораторные работы по Linux
site_description: Документация по выполнению лабораторных работ по администрированию Linux Ubuntu
site_author: Биктагирова Зарина

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
  palette:
    - scheme: default
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: dark
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Главная: index.md
  - Лабораторная работа 1: 
    - Описание: lab1/index.md
    - Задание 1: lab1/task1.md
    - Задание 2: lab1/task2.md
    - Задание 3: lab1/task3.md
    - Задание 4: lab1/task4.md
    - Задание 5: lab1/task5.md
    - Задание 6: lab1/task6.md
    - Задание 7: lab1/task7.md
    - Задание 8: lab1/task8.md
    - Задание 9: lab1/task9.md
    - Задание 10: lab1/task10.md
    - Проверка: lab1/verification.md
  - Приложения: appendix.md

markdown_extensions:
  - admonition
  - codehilite
  - tables
  - pymdownx.superfences

extra_css:
  - stylesheets/extra.css

plugins:
  - search
